idf_component_register(SRCS "pm_manager.c" "ota_update.c" "filter_manager.c" "history_logger.c" "main.c"
                    "gpio_driver.c"
                    "tds_sensor.c"
                    "water_purifier_fsm.c"
                    "wifi_manager.c"
                    "mqtt_client.c"
                    "web_server.c"
                    "config_manager.c"
                    INCLUDE_DIRS "." "include"
                    REQUIRES driver esp_wifi esp_event mqtt esp_http_server esp_adc esp_driver_gpio cjson nvs_flash esp_app_format esp_partition app_update esp_pm)